fix waiter's promotion algorithm
kzub/basketball2 pull request #1
Opened 2019-08-28 23:34 UTC by MolotD

promote waiter to player only if player (not waiter) has canceled
reservation

2019-08-29 09:33 UTC, kzub requested changes
надо проще сделать, если джун, то не промоутить
все функции уже есть

2019-08-29 09:33 UTC, kzub commented on back/dal/types.js
> +Reservation.prototype.isPlayer = function () {
Это не верно, статусы могут быть другими, например booked
PLayer это тот кто не Waiter, надо на это опираться

2019-08-29 09:33 UTC, kzub commented on back/api/reservation.js
> +  const isPlayer = reservation.isPlayer();
в отдельную переменную нет смысла выносить, с isWaiter это сделано для удобства передачи в качесте параметра объекта в { reservation, isWaiter }

2019-08-29 19:22 UTC, MolotD commented on back/api/reservation.js
> +  const isPlayer = reservation.isPlayer();
Если не сохранить в отдельную переменную, то строчка reservation.cancel(); поставит статус в canceled.

2020-10-04 13:15 UTC, closed without merging

2020-10-04 13:15 UTC, kzub commented
fixed